# Bitcoin
# Bitcoin Cash
# Ethereum
# BNB Smart Chain
custom: ["https://link.trustwallet.com/send?coin=0&address=bc1qa948wr4mg2qkx2us5g8rv5ca75ppyy2ngl8k4e","https://link.trustwallet.com/send?coin=145&address=qrrj03927q90z4wg4nu2e3nf4y3qnun2ku7muv8rvm","https://link.trustwallet.com/send?coin=60&address=0xF784a3D4F9A7CC5c26d69de41D7dD6480112114D","https://link.trustwallet.com/send?coin=20000714&address=0xF784a3D4F9A7CC5c26d69de41D7dD6480112114D"]
